- numpy is the fundamental package for scientific computing in Python. Used to multidimensional array objects like masked arrays and matrices
- operations likes sorting, selecting, discrete fourier transforms, basic linear algebra, bsic statistical operations, random simulation

## Vectorization and Broadcasting
- Vectorization in NumPy is the practice of performing mathematical operations on entire arrays at once instead of looping through individual elements
- Broadcasting in NumPy is a mechanism that allows arithmetic operations to be performed on arrays of different shapes

In [1]:
import numpy as np

In [34]:
array: np.ndarray = np.array([1, 2, 3, 4, 5])

In [18]:
array.ndim # gives the dimension of the numpy array (number of axes)

(2, 0)

In [35]:
array.shape # gives you the number of n rows and m columns in the form of tupel

(5,)

In [37]:
array.size # gives you the total number of elements inn the array.

5

In [39]:
array.dtype # gives you the the type of the array

dtype('int64')

In [41]:
array.itemsize # gives you the size of item in python float64 is double in c

8

In [45]:
array.data # gives the buffer of the array

# Array Creation


In [46]:
np.array([[1, 2], [3, 4]], dtype=complex) # dtype keyword used to give the datatype during array creation

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [48]:
np.array([[1, 2], [3, 4]], dtype=float).dtype

dtype('float64')

In [49]:
np.array(0)

array(0)

In [54]:
np.zeros((2, 3, 4)) # -> it creates a dimensional array of size n,m and fill it with the zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [53]:
# similarly we have np.ones
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [56]:
# he function empty creates an array whose initial content is random and depends on the state of the memory.
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
# arange function is used to create the sequence of numbers with a step value.
np.arange(0, 2, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [67]:
# to have control on the number of elements we use linspace instead of arange function
np.linspace(0, 2, 9)
# and the step is calcualted by (stop - start)/ interval(number of elements - 1)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [72]:
any([True, False])

True

In [85]:
# printing arrays
np.arange(10000).reshape((50, 100, 2))

array([[[   0,    1],
        [   2,    3],
        [   4,    5],
        ...,
        [ 194,  195],
        [ 196,  197],
        [ 198,  199]],

       [[ 200,  201],
        [ 202,  203],
        [ 204,  205],
        ...,
        [ 394,  395],
        [ 396,  397],
        [ 398,  399]],

       [[ 400,  401],
        [ 402,  403],
        [ 404,  405],
        ...,
        [ 594,  595],
        [ 596,  597],
        [ 598,  599]],

       ...,

       [[9400, 9401],
        [9402, 9403],
        [9404, 9405],
        ...,
        [9594, 9595],
        [9596, 9597],
        [9598, 9599]],

       [[9600, 9601],
        [9602, 9603],
        [9604, 9605],
        ...,
        [9794, 9795],
        [9796, 9797],
        [9798, 9799]],

       [[9800, 9801],
        [9802, 9803],
        [9804, 9805],
        ...,
        [9994, 9995],
        [9996, 9997],
        [9998, 9999]]], shape=(50, 100, 2))

# Arthemetic Operations using NumPY

In [91]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [92]:
a - b

array([20, 29, 38, 47])

In [93]:
3 * a

array([ 60,  90, 120, 150])

In [94]:
a ** 2

array([ 400,  900, 1600, 2500])

In [95]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

# Element wise product and Matrix product

In [101]:
a = np.linspace(2, 10, 6, dtype="int64").reshape(2, 3)
b = np.linspace(0, 6, 6, dtype="int64").reshape(2, 3)

In [104]:
a

array([[ 2,  3,  5],
       [ 6,  8, 10]])

In [105]:
b

array([[0, 1, 2],
       [3, 4, 6]])

In [106]:
a + b

array([[ 2,  4,  7],
       [ 9, 12, 16]])

In [107]:
a * b

array([[ 0,  3, 10],
       [18, 32, 60]])

In [112]:
# matrix product
a = np.linspace(2, 10, 4, dtype="int64").reshape(2, 2)
b = np.linspace(0, 6, 4, dtype="int64").reshape(2, 2)

In [113]:
print(a, b)

[[ 2  4]
 [ 7 10]] [[0 2]
 [4 6]]


In [114]:
a @ b

array([[16, 28],
       [40, 74]])

In [115]:
a.dot(b)

array([[16, 28],
       [40, 74]])

In [116]:
# all the arthemetics operations takes place in the existing array.

In [117]:
a

array([[ 2,  4],
       [ 7, 10]])

In [118]:
a < 36

array([[ True,  True],
       [ True,  True]])

In [120]:
10 * np.sin(a) # -> the param is in radians

array([[ 9.09297427, -7.56802495],
       [ 6.56986599, -5.44021111]])

In [139]:
rg = np.random.default_rng(1)  # create instance of default random number generator -> default rng acts as constructor to use its static functions.


In [137]:
rg

Generator(PCG64) at 0x277DCF6D000

# Generator in Python

In [126]:
from collections.abc import Generator 
def count_up_to_n(n) -> Generator[int]:
    count: int = 1 
    while count <= n:
        yield count
        count += 1

In [138]:
for i in count_up_to_n(5):
    print(i)

count_up_to_n(5)

1
2
3
4
5


<generator object count_up_to_n at 0x00000277DCF95780>

In [128]:
def advanced_echo() -> Generator[str, int, bool]:
    value = yield "Ready"
    if value == 42:
        return True
    return False

In [130]:
advanced_echo()

<generator object advanced_echo at 0x00000277DC5CB340>

In [132]:
g = advanced_echo()
print(next(g))  # start the generator, yields "Ready"
try:
    g.send(42)
except StopIteration as e:
    print(e.value)  # prints the returned value (True/False)

Ready
True


In [148]:
3 * np.ones((2, 3), dtype=int)

array([[3, 3, 3],
       [3, 3, 3]])

In [162]:
rg.random((2, 2)).sum() # similarly min() and max()

np.float64(1.1714804379303787)

In [149]:
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])

In [156]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [160]:
np.exp(c * 1j) # e^ci -> np.cos(c) + np.sin(c)*1j

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [167]:
b = np.arange(12).reshape(3, 4)

In [168]:
# if axis is zero meant operation is on column otherwise on 1 it's a row
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [170]:
b.sum(axis=1)

array([ 6, 22, 38])

In [174]:
b.cumsum(axis=0) 

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

# Universal functions
- NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.



In [177]:
# np.fromfunction() -> is used to generate elements based on the specific logic given by a callback function (cb, shape, dtype)

In [176]:
# 1. Define a function with two parameters: 'row' and 'col'
def add_coordinates(row, col):
    print("Row parameter received:\n", row)
    print("Col parameter received:\n", col)
    return row + col

# 2. Call fromfunction with a shape of (2, 3)
result = np.fromfunction(add_coordinates, (2, 3), dtype=int)

print("\nFinal Result Array:\n", result)

Row parameter received:
 [[0 0 0]
 [1 1 1]]
Col parameter received:
 [[0 1 2]
 [0 1 2]]

Final Result Array:
 [[0 1 2]
 [1 2 3]]


In [183]:
a = np.fromfunction(lambda x, y: 10 * x + y, (5,4), dtype="int64" )

In [184]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [187]:
for idx, row in enumerate(a):
    print(idx, row)

0 [0 1 2 3]
1 [10 11 12 13]
2 [20 21 22 23]
3 [30 31 32 33]
4 [40 41 42 43]


In [188]:
# flat -> is the iterator over all elements
for ele in a.flat:
    print(ele)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape Manipulation

In [204]:
a = np.floor(10 * rg.random((3, 4)))

In [198]:
# ravel() -> used to make the array flat
a.ravel()
a

array([[0., 0., 2., 4.],
       [4., 8., 3., 0.],
       [8., 0., 0., 9.]])

In [205]:
a.reshape(3, 4)

array([[7., 3., 1., 3.],
       [3., 8., 4., 0.],
       [9., 6., 1., 1.]])

In [206]:
a

array([[7., 3., 1., 3.],
       [3., 8., 4., 0.],
       [9., 6., 1., 1.]])

In [203]:
a.T.shape # -> T  used to transpose a given array

(4, 3)

In [207]:
#  Stacking together different arrays
a = np.floor(10 * rg.random((2, 2)))
a
b = np.floor(10 * rg.random((2, 2)))
b
np.vstack((a, b))
np.hstack((a, b))

array([[4., 0., 0., 8.],
       [6., 6., 7., 9.]])